name: CI

on:
  push:
    branches: [main, master, trunk, "release/*"]
  pull_request:
    branches: ["**"]

env:
  PYTHON_VERSION: "3.13"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        run: uv python install ${{ env.PYTHON_VERSION }}

      - name: Install dependencies (locked)
        run: uv sync --frozen --extra dev

      - name: Lint (ruff)
        run: uv run ruff check .

      - name: Cache mypy cache
        uses: actions/cache@v4
        with:
          path: .mypy_cache
          key: mypy-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            mypy-${{ runner.os }}-

      - name: Type check (mypy)
        run: uv run mypy --sqlite-cache --pretty src tests

      - name: Test (pytest)
        run: uv run pytest -q

  # Deploy is implemented as a reusable workflow so it can depend on lint-and-test via `needs`.
  deploy:
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
    needs: lint-and-test
    uses: ./.github/workflows/deploy.yml
    # Provide inputs to override defaults if desired.
    # with:
    #   service_user: "uv-package-template"
    #   service_name: "uv-package-template"
    #   app_user_root: "/opt/uv-package-template"
    #   app_dir: "uv-package-template/uv-package-template"
    #   concurrency_group: "uv-package-template-prod"
    secrets: inherit
